# Generated by Django 2.0.7 on 2018-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='Точность'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='double',
            field=models.IntegerField(default=0, verbose_name='Двойной'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='inner',
            field=models.IntegerField(default=0, verbose_name='Внутренний'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='is_range',
            field=models.IntegerField(default=0, verbose_name='Дистанция'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='misshot',
            field=models.IntegerField(default=0, verbose_name='Промах'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='oneshot',
            field=models.IntegerField(default=0, verbose_name='Первый бросок'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='outer',
            field=models.IntegerField(default=0, verbose_name='Внешний'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='shoots',
            field=models.IntegerField(default=0, verbose_name='Броски'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='sibling',
            field=models.IntegerField(default=0, verbose_name='Сиблинг'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='single',
            field=models.IntegerField(default=0, verbose_name='Один'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='threeshot',
            field=models.IntegerField(default=0, verbose_name='Третий бросок'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='triple',
            field=models.IntegerField(default=0, verbose_name='Тройной'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='twoshot',
            field=models.IntegerField(default=0, verbose_name='Второй бросок'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='zero',
            field=models.IntegerField(default=0, verbose_name='Зеро'),
        ),
    ]
