# Generated by Django 2.0.7 on 2018-07-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180725_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='avatar',
        ),
    ]
