# Generated by Django 2.0.7 on 2018-07-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_userstats_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='avatar',
            field=models.IntegerField(blank=True, default=0, verbose_name='Аватар'),
        ),
    ]
