# Generated by Django 2.0.7 on 2018-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20180726_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='is_range',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='win',
        ),
        migrations.AddField(
            model_name='userstats',
            name='another',
            field=models.IntegerField(default=0, verbose_name='Другой'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='big',
            field=models.IntegerField(default=0, verbose_name='Большой'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='games',
            field=models.IntegerField(default=0, verbose_name='Игр'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='maxScores',
            field=models.IntegerField(default=0, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='middleMiss',
            field=models.IntegerField(default=0, verbose_name='Средний промах'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='minScores',
            field=models.IntegerField(default=0, verbose_name='Минимальный балл'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='small',
            field=models.IntegerField(default=0, verbose_name='Маленький'),
        ),
    ]
