# Generated by Django 2.0.7 on 2018-07-26 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20180726_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='minScores',
            field=models.IntegerField(default=9999, verbose_name='Минимальный балл'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='globalStats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
